### ISSUE TITLE
Is chn.residual_out missing in config/global/default.yaml ?

### ISSUE THREAD

**Issue by serjordan** [mindslab-ai/assem-vc#12]
Hello!
Thank you for your awesome project!

1). I believe `hp.chn.residual_out` in [modules/vc_decoder.py](https://github.com/mindslab-ai/assem-vc/blob/master/modules/vc_decoder.py) line 54 should be defined in [config/global/default.yaml,](https://github.com/mindslab-ai/assem-vc/blob/master/config/global/default.yaml) right?
2). Why were `libritts_vctk_train_10s_g2p.txt` and `libritts_vctk_val_g2p.txt` files deleted from the repo? Shouldn't we use them as `train_meta` and `val_meta` in [config/global/default.yaml](https://github.com/mindslab-ai/assem-vc/blob/master/config/global/default.yaml) ?

**Comment by wookladin** [comment]
Hi!
1) Yeah, you pointed out correctly.
The value of `hp.chn.residual_out` should be 1.
I made a mistake while deleting legacy :(  
Sorry. I will modify it on the next commit.
2) Also you are right.
However, in uploaded `libri_vctk` metadata, the speech location of VCTK corpus was written incorrectly.
I deleted that file since it can cause confusion for users.
You can use it after merging the metadata of LibriTTS and VCTK.
This will also be added in the next commit.

We will pin this issue until it is resolved.
This is my first open-source release, so there are a lot of mistakes. ​
Thanks for the important feedback :)
