### ISSUE TITLE
Which Hi-Fi gan version did you use?

### ISSUE THREAD

**Issue by faranaziz** [mindslab-ai/assem-vc#3]
Can you indicate which git repo? Official or unofficial? and the Mel is it still 70-800 or 0-8000? 

Thanks you

**Comment by seungwonpark** [comment]
The first author is temporarily unavailable due to his mandatory military service (he'll come back on May 20), so I'll answer.

I do not remember such details of our implementation, but either using official/unofficial version and 70-8k/0-8k will be all okay. However, if you're using https://github.com/mindslab-ai/cotatron, make sure that such configurations are identical across acoustic model and the vocoder. In this case, perhaps https://github.com/mindslab-ai/cotatron/issues/14 will be helpful for you.

**Comment by faranaziz** [comment]
Thanks you very much.

**Comment by wookladin** [comment]
We used the same mel configuration and mel calculation script with [official HiFi-GAN repo](https://github.com/jik876/hifi-gan).
That is, we used the settings of f_min=0 and f_max=8000.
