### ISSUE TITLE
Audio samples sound great! I have a few questions.

### ISSUE THREAD

**Issue by Iamgoofball** [mindslab-ai/assem-vc#5]
Hello! 

Very excited for the code release this June, I'm interested to see how my datasets hold up when trained with your model. I've got a few questions so that I can adequately prep my datasets:

1. Do I only need audio to train a speaker, or do I need audio + text transcriptions?
2. What specific format and specifications should the audio be in?
3. Do the speakers need to have the exact same utterances to train, or can they be different utterances?
4. Do you think this model would be able to perform well doing Any to Many or Many to Many real-time? For example, if the input speaker was a microphone feed.

Thanks for reading, good luck w/ the code release!

**Comment by wookladin** [comment]
Hi.
Thanks for your interest in our work :)

Here's my answer to your questions.

1. You need audio + text transcriptions both.
2. About our format, you can refer to https://github.com/mindslab-ai/cotatron/tree/master/datasets/metadata . You need to make metadata that contains the audio file's location and transcription of it.
3. Since our work is focused on non-parallel voice conversion, they can be different utterances.
4. Since our model is based on the attention of TTS, full audio and corresponding transcription is needed. Hence I think it is hard to applicate in a real-time situation.
